# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

title: Con Alma tech
email: analaura.almada@conalma.tech
description: >- # this means to ignore newlines until "baseurl:"
  Espacio de aprendizaje para usar la tecnología a nuestro favor.
  Servicios de soporte técnico, consultoría y capacitación tecnológica.
  Blog de tecnología, software libre y cultura digital.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anitalmada.github.io" # the base hostname & protocol for your site, e.g. http://example.com
keywords: "educación - tecnología- cultura digital - soporte técnico - consultoría tecnológica - capacitación tecnológica"
skills: "Consultora - Docente - Speaker"
meta_author: Ana Almada

contact: static

color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

social:
  - title: instagram
    url: https://www.instagram.com/conalma.tech/
  - title: whatsapp
    url: https://wa.me/5491127895799
  - title: linkedin
    url: https://www.linkedin.com/in/anitalmada/

address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      permalink: "/blog/:title/"

# Build settings
theme: null
plugins:
  - jekyll-feed

# Force index page
index_page: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
